api_platform:
    title: Hello API Platform
    version: 1.0.0
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
        csv: ['text/csv']
    defaults:
        stateless: false
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    # set up the swagger configuration
    swagger:
        api_keys:
            access_token:
                name: Authorization
                type: header