twig:
    file_name_pattern: '*.twig'
    paths:
        '%kernel.project_dir%/assets/styles': styles
        '%kernel.project_dir%/assets/imgs': images # can access this imgs directory in twig with @images

when@test:
    twig:
        strict_variables: true
